export let products = [
  {
    id: 1,
    title: "Carhatt Jacket",
    price: 65000,
    stock: 4,
    description: "Campera carhatt con diseño unico",
    category: "Top",
    img: "https://res.cloudinary.com/dduq6njfw/image/upload/v1697325046/ctasyl1vvqnbou0ypw2k.png",
    discount: 50000,
  },
  {
    id: 2,
    title: "Cammo Pant",
    price: 34500,
    stock: 2,
    description: "Pantalon de tipo camuflaje, tela de diseño",
    category: "Pants",
    img: "https://res.cloudinary.com/dduq6njfw/image/upload/v1697325086/nj8jwgcyvpqqizm3op0r.png",
    discount: 20000,
  },
  {
    id: 3,
    title: "Blow-Up T-Shirt",
    price: 19000,
    stock: 3,
    description:
      "Blow your drama... Remera crop con box fit, holgada para mas comodidad",
    category: "Top",
    img: "https://res.cloudinary.com/dduq6njfw/image/upload/v1697325073/otlulpakmmnopv5jzhtv.png",
    discount: 15000,
  },
  {
    id: 4,
    title: "Smoke T-Shirt",
    price: 17800,
    stock: 5,
    description: "Fumar mata, Remera crop, estampado azul con serigrafia",
    category: "Top",
    img: "https://res.cloudinary.com/dduq6njfw/image/upload/v1697325676/qyngibwbsiurzbm2wikt.jpg",
    discount: 13000,
  },
  {
    id: 5,
    title: "Evisu shorts",
    price: 44500,
    stock: 2,
    description: "Long live Nigo, short original de evisu",
    category: "Pants",
    img: "https://res.cloudinary.com/dduq6njfw/image/upload/v1697414524/jw7utnvsaooo3gbw0ft6.png",
    discount: 40000,
  },
];
